controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_reservation:
    path: /reservation{id}
    controller: App\Controller\ReservationController::reserveRoomAction
    methods: [GET, POST]
    
reservation_success:
    path: /reservation/success
    controller: App\Controller\ReservationController::success

reservation_delete:
    path: /reservation/{id}/delete
    controller: App\Controller\ReservationController::delete